---
title: "Exploratory Analysis"
author: "B. D. Schedin"
date: "10/1/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

projRoot <- "C:/_git_/student-performance-analysis/"

library(tidyverse)
library(ggcorrplot)
library(randomForest)

source(paste0(projRoot, "functions/diag-accuracy.R"))

```

# Data Preprocessing
```{r}

# Loading and combining raw data
d1 <- read.table(paste0(projRoot, "data/raw/student-mat.csv"), sep=";", header=TRUE)
d2 <- read.table(paste0(projRoot, "data/raw/student-por.csv"), sep=";", header=TRUE)

full <- bind_rows(d1, d2)

# Checking for duplicate rows
sum(duplicated(full) == FALSE)

# Checking for missing values by column
sapply(full, function(x) sum(is.na(x)))

# Replacing period grades with average (gMean)
full$gMean <- rowMeans(full[, 31:33])

# Exporting merged data to .csv
write.csv(full, paste0(projRoot, "data/processed/full.csv"), row.names=FALSE)

# Filtering on numeric data for prototype numeric analyses (not re-encoded)
fullNum <- full %>%
  select(where(is.numeric))

```

# Demographics
```{r}

# Stacked bar plot for age and gender
test <- full %>% count(age, sex)

ggplot(test, aes(fill=sex, y=n, x=age)) +
  geom_bar(position="stack", stat="identity") +
  scale_x_continuous(breaks=round(seq(min(test$age), max(test$age), by=1))) +
  theme_bw() +
  labs(title="Age", x="Age", y="Count")

```

# Student Culture
```{r}

# Failures
temp <- full %>% count(failures, sex)

ggplot(temp, aes(fill=sex, x=failures, y=n)) +
  geom_bar(position="stack", stat="identity") +
  scale_x_continuous(breaks=round(seq(min(temp$failures), max(temp$failures), by=1))) +
  theme_bw() +
  labs(title="Course Failures", x="Number of Failures", y="Count")

# Absences
temp <- full %>% count(absences, sex)

ggplot(data=temp, aes(x=absences, y=n, group=sex)) +
  geom_smooth(aes(color=sex), se=FALSE) +
  theme_bw() +
  labs(title="Absences", x="Number of Absences", y="Number of Students")

# Study time
temp <- full %>% count(studytime, sex)

ggplot(temp, aes(fill=sex, x=studytime, y=n)) +
  geom_bar(position="stack", stat="identity") +
  scale_x_continuous(breaks=round(seq(min(temp$studytime), max(temp$studytime), by=1))) +
  theme_bw() +
  labs(title="Study Time", x="Hours Spent", y="Count")

# Free time
temp <- full %>% count(freetime, sex)

ggplot(temp, aes(fill=sex, x=freetime, y=n)) +
  geom_bar(position="stack", stat="identity") +
  scale_x_continuous(breaks=round(seq(min(temp$freetime), max(temp$freetime), by=1))) +
  theme_bw() +
  labs(title="Free Time", x="Hours Spent", y="Count")

```


# Grade Distributions
```{r}

# Box plots period grades
full %>% 
  select(school, G1, G2, G3) %>% 
  reshape2::melt(id="school") %>% 
    ggplot(aes(x=variable, y=value)) + 
    geom_boxplot(aes(fill=school)) +
    theme_bw() +
    labs(title="Grades by Class Period", x="Period", y="Score")

# Density plots for student grades during each class period
full %>% 
  select(school, G1) %>% 
    ggplot(aes(x=G1, fill=school)) +
    geom_density(alpha=0.25) +
    theme_bw() +
    labs(title="1st Period Grades", x="Score", y="Density")

full %>% 
  select(school, G2) %>% 
    ggplot(aes(x=G2, fill=school)) +
    geom_density(alpha=0.25) +
    theme_bw() +
    labs(title="2nd Period Grades", x="Score", y="Density")

full %>% 
  select(school, G3) %>% 
    ggplot(aes(x=G3, fill=school)) +
    geom_density(alpha=0.25) +
    theme_bw() +
    labs(title="3rd Period Grades", x="Score", y="Density")

full %>% 
  select(school, gMean) %>% 
    ggplot(aes(x=gMean, fill=school)) +
    geom_density(alpha=0.25) +
    theme_bw() +
    labs(title="Average Grades (All Periods)", x="Score", y="Density")

# Selecting students that scored below threshold during each period
threshold <- 2.5

g1BelowScore <- full %>%
  select(everything()) %>%
  filter(G1 <= threshold) %>%
  as_tibble()
g1BelowScore

g2BelowScore <- full %>%
  select(everything()) %>%
  filter(G2 <= threshold) %>%
  as_tibble()
g2BelowScore

g3BelowScore <- full %>%
  select(everything()) %>%
  filter(G3 <= threshold) %>%
  as_tibble()
g3BelowScore

# TODO: in dashboard, provide check boxes to show/hide columns
# TODO: dig deeper into why students are scoring lower during later periods (hypothesis tests?)
# TODO: look at top performers for clues about performance factors

```

A large tail appears near 0 as the day goes on.
Distributions narrow to the mean as the day goes on.
GP outperforms MS across the board.

# Performance Correlations
```{r}

# Computing correlations between variables
varCor <- cor(fullNum)

# Plotting correlation table
ggcorrplot(varCor) + 
  theme(axis.text.x = element_text(size=11, angle=90, hjust=0.99, vjust=0.3), axis.text.y=element_text(size=11)) + 
  labs(title = "Variable Correlations", x="Variable 1", y="Variable 2")

# TODO: are all numeric variables continuous, or are they really factors encoded as numbers?
# TODO: good way to do correlations between factors/non-numeric?

```

# Performance Prediction
```{r}

# Setting the seed for the chunk
set.seed(123)

# Replacing period grades with average (gMean)
forestDat <- full
forestDat <- forestDat[, -c(31:33)]

# Labeling students with grades above 10 as a success, removing gMean
threshold <- 10
forestDat <- forestDat %>% mutate(label = if_else(gMean < threshold, "Below", "Above")) %>% select(-gMean)
forestDat$label <- as.factor(forestDat$label)

# Checking for sample bias
table(forestDat$label)

# Splitting the data into train and test sets (50-50 split)
trainIndices <- sample(1:nrow(forestDat), 0.50*nrow(forestDat), replace=FALSE)

train <- forestDat[trainIndices, ]
test <- forestDat[-trainIndices, ]

# Building the model
rf <- randomForest(label ~ ., data=train, ntree=50)
rfPred <- predict(rf, test)

# Reporting test accuracy
testPred <- table(predicted=rfPred, truth=test$label)
testPred

cat("Test accuracy: ", accuracyDiag(testPred), "%\n", sep="")

```

# Categorical Variable Re-encoding
```{r}

# TODO: Implement

```

# Stepwise Regression
```{r}

# TODO: Implement

```

# Clustering
```{r}

# TODO: Implement

```

# Multinomial Logistic Regression
```{r}

# TODO: Implement

```










